name: Continuous Integration

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Compile contracts
      run: npm run compile
